"""Supabase/Postgres connection layer for the ICON MOBILE store.

The original application used ``sqlite3`` with a ``conn.execute(sql, params)``
API and ``?`` placeholders.  To keep the ported store logic faithful and easy
to compare against ``backend_store.py``, this module exposes a thin
``PgConnection`` wrapper with the same ``.execute()`` shape on top of
``psycopg2``.  The ported SQL uses ``%s`` placeholders (psycopg2) and relies on
the ``citext`` extension for the case-insensitive unique columns that were
``TEXT COLLATE NOCASE`` in SQLite.
"""

from __future__ import annotations

import os
import threading
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Iterator, Optional, Sequence

import psycopg2
from dotenv import load_dotenv
from psycopg2 import extras, pool

load_dotenv(Path(__file__).resolve().parents[3] / ".env")

_pool: Optional[pool.ThreadedConnectionPool] = None
_pool_lock = threading.Lock()


def _dsn() -> str:
    dsn = os.environ.get("SUPABASE_DB_URL", "").strip()
    if not dsn:
        raise RuntimeError(
            "SUPABASE_DB_URL must be set to the Supabase Postgres connection "
            "string (Project Settings -> Database -> Connection string -> URI)."
        )
    return dsn


def get_pool() -> pool.ThreadedConnectionPool:
    global _pool
    with _pool_lock:
        if _pool is None:
            _pool = pool.ThreadedConnectionPool(1, 12, dsn=_dsn())
    return _pool


class _Empty:
    """Return value for BEGIN/COMMIT/ROLLBACK so callers can chain safely."""

    rowcount = 0
    lastrowid = None

    def fetchone(self) -> Any:
        return None

    def fetchall(self) -> list:
        return []


class PgConnection:
    """psycopg2 adapter with a sqlite3-style ``.execute()`` method.

    ``execute("COMMIT")`` / ``execute("ROLLBACK")`` map to the real transaction
    controls; ``execute("BEGIN")`` is a no-op because psycopg2 opens a
    transaction implicitly on the first statement.  Every other statement runs
    through a ``DictCursor`` whose rows support both ``row[0]`` and
    ``row["column"]`` access, matching ``sqlite3.Row``.
    """

    def __init__(self, raw: Any) -> None:
        self.raw = raw

    def execute(self, sql: str, params: Sequence[Any] = ()) -> Any:
        control = sql.strip().upper()
        if control == "COMMIT":
            self.raw.commit()
            return _Empty()
        if control == "ROLLBACK":
            self.raw.rollback()
            return _Empty()
        if control in ("BEGIN", "BEGIN IMMEDIATE"):
            return _Empty()
        cursor = self.raw.cursor(cursor_factory=extras.DictCursor)
        cursor.execute(sql, params)
        return cursor


@contextmanager
def connection(*, read_only: bool = False) -> Iterator[PgConnection]:
    handle = get_pool()
    raw = handle.getconn()
    raw.autocommit = False
    try:
        yield PgConnection(raw)
        raw.commit()
    except Exception:
        raw.rollback()
        raise
    finally:
        handle.putconn(raw)


# ---------------------------------------------------------------------------
# Schema.  Translated from the SQLite v2 schema in backend_store.py:
#  * INTEGER PRIMARY KEY  -> BIGINT GENERATED BY DEFAULT AS IDENTITY
#    (BY DEFAULT lets a restore re-insert explicit ids)
#  * TEXT COLLATE NOCASE UNIQUE -> CITEXT UNIQUE (case-insensitive equality)
#  * PRAGMA / WAL removed; Postgres enforces foreign keys natively
# ---------------------------------------------------------------------------

SCHEMA_STATEMENTS = [
    "CREATE EXTENSION IF NOT EXISTS citext;",
    """
    CREATE TABLE IF NOT EXISTS v2_meta (
        key TEXT PRIMARY KEY,
        value TEXT NOT NULL
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS v2_products (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        sku CITEXT NOT NULL UNIQUE,
        item_type TEXT NOT NULL DEFAULT '',
        category TEXT NOT NULL DEFAULT '',
        brand TEXT NOT NULL DEFAULT '',
        model TEXT NOT NULL DEFAULT '',
        color TEXT NOT NULL DEFAULT '',
        specs_json TEXT NOT NULL DEFAULT '{}',
        price_cents BIGINT NOT NULL DEFAULT 0 CHECK (price_cents >= 0),
        offer_price_cents BIGINT NOT NULL DEFAULT 0 CHECK (offer_price_cents >= 0),
        aggregate_quantity INTEGER NOT NULL DEFAULT 0 CHECK (aggregate_quantity >= 0),
        notes TEXT NOT NULL DEFAULT '',
        legacy_json TEXT NOT NULL DEFAULT '{}',
        deleted INTEGER NOT NULL DEFAULT 0 CHECK (deleted IN (0, 1)),
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        revision BIGINT NOT NULL DEFAULT 0
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS v2_units (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        product_id BIGINT NOT NULL REFERENCES v2_products(id) ON DELETE RESTRICT,
        unit_code CITEXT NOT NULL UNIQUE,
        supplier TEXT NOT NULL DEFAULT '',
        cost_cents BIGINT NOT NULL DEFAULT 0 CHECK (cost_cents >= 0),
        status TEXT NOT NULL DEFAULT 'Available'
            CHECK (status IN ('Available', 'Sold', 'Returned', 'Deleted') OR status LIKE 'Partner:%'),
        date_added TEXT NOT NULL,
        deleted INTEGER NOT NULL DEFAULT 0 CHECK (deleted IN (0, 1)),
        updated_at TEXT NOT NULL,
        revision BIGINT NOT NULL DEFAULT 0
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS v2_clients (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        client_key CITEXT NOT NULL UNIQUE,
        name TEXT NOT NULL,
        phone TEXT NOT NULL DEFAULT '',
        email TEXT NOT NULL DEFAULT '',
        client_type TEXT NOT NULL DEFAULT 'Retail' CHECK (client_type IN ('Retail', 'B2B')),
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        revision BIGINT NOT NULL DEFAULT 0
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS v2_transactions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        invoice_id CITEXT NOT NULL UNIQUE,
        client_id BIGINT REFERENCES v2_clients(id) ON DELETE RESTRICT,
        transaction_type TEXT NOT NULL
            CHECK (transaction_type IN ('Sale', 'Issue', 'Return', 'B2B_Payment')),
        record_type TEXT NOT NULL DEFAULT '',
        source_system TEXT NOT NULL DEFAULT '',
        client_name TEXT NOT NULL DEFAULT '',
        client_phone TEXT NOT NULL DEFAULT '',
        client_email TEXT NOT NULL DEFAULT '',
        payment_method TEXT NOT NULL DEFAULT '',
        subtotal_cents BIGINT NOT NULL DEFAULT 0,
        discount_cents BIGINT NOT NULL DEFAULT 0,
        total_cents BIGINT NOT NULL DEFAULT 0,
        quantity INTEGER NOT NULL DEFAULT 0,
        linked_invoice_id CITEXT NOT NULL DEFAULT '',
        request_hash TEXT NOT NULL,
        raw_json TEXT NOT NULL,
        created_at TEXT NOT NULL,
        revision BIGINT NOT NULL
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS v2_transaction_items (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        transaction_id BIGINT NOT NULL REFERENCES v2_transactions(id) ON DELETE RESTRICT,
        product_id BIGINT REFERENCES v2_products(id) ON DELETE RESTRICT,
        unit_id BIGINT REFERENCES v2_units(id) ON DELETE RESTRICT,
        unit_code CITEXT NOT NULL DEFAULT '',
        group_code TEXT NOT NULL DEFAULT '',
        quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
        price_cents BIGINT NOT NULL DEFAULT 0,
        discount_cents BIGINT NOT NULL DEFAULT 0,
        cost_cents BIGINT NOT NULL DEFAULT 0,
        raw_json TEXT NOT NULL
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS v2_operation_receipts (
        operation_id TEXT PRIMARY KEY,
        device_id TEXT NOT NULL,
        actor_role TEXT NOT NULL,
        action TEXT NOT NULL,
        request_hash TEXT NOT NULL,
        invoice_id CITEXT NOT NULL DEFAULT '',
        revision BIGINT NOT NULL,
        response_json TEXT NOT NULL,
        created_at TEXT NOT NULL
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS v2_change_log (
        revision BIGINT PRIMARY KEY,
        operation_id TEXT NOT NULL,
        device_id TEXT NOT NULL,
        actor_role TEXT NOT NULL,
        action TEXT NOT NULL,
        entity_type TEXT NOT NULL,
        entity_id TEXT NOT NULL,
        summary_json TEXT NOT NULL,
        created_at TEXT NOT NULL
    );
    """,
    "CREATE INDEX IF NOT EXISTS ix_v2_products_updated ON v2_products(deleted, updated_at DESC);",
    "CREATE INDEX IF NOT EXISTS ix_v2_units_product ON v2_units(product_id, deleted, status);",
    "CREATE INDEX IF NOT EXISTS ix_v2_clients_updated ON v2_clients(updated_at DESC, id DESC);",
    "CREATE INDEX IF NOT EXISTS ix_v2_clients_name ON v2_clients(lower(name));",
    "CREATE INDEX IF NOT EXISTS ix_v2_transactions_created ON v2_transactions(created_at DESC, id DESC);",
    "CREATE INDEX IF NOT EXISTS ix_v2_transactions_type ON v2_transactions(transaction_type, created_at DESC);",
    "CREATE INDEX IF NOT EXISTS ix_v2_transaction_items_unit ON v2_transaction_items(unit_code);",
    "CREATE INDEX IF NOT EXISTS ix_v2_receipts_created ON v2_operation_receipts(created_at DESC);",
]

SEED_META = [
    ("schema_version", None),  # filled from SCHEMA_VERSION at init time
    ("revision", "0"),
    ("backup_interval_days", "7"),
    ("automatic_backup_interval_hours", "24"),
]


def init_db(schema_version: str) -> None:
    """Create every table/index if missing.  Idempotent; safe on each startup."""
    handle = get_pool()
    raw = handle.getconn()
    try:
        raw.autocommit = True
        with raw.cursor() as cursor:
            for statement in SCHEMA_STATEMENTS:
                cursor.execute(statement)
            cursor.execute(
                "INSERT INTO v2_meta(key, value) VALUES(%s, %s) ON CONFLICT (key) DO NOTHING",
                ("schema_version", schema_version),
            )
            for key, value in SEED_META:
                if value is None:
                    continue
                cursor.execute(
                    "INSERT INTO v2_meta(key, value) VALUES(%s, %s) ON CONFLICT (key) DO NOTHING",
                    (key, value),
                )
    finally:
        raw.autocommit = False
        handle.putconn(raw)
